---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloads-manager
rules:
  - apiGroups:
      - workloads.crd.gocardless.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - "jobs"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - "*"
  - apiGroups:
      - ""
      - admissionregistration.k8s.io
    resources:
      - services
      - events
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - "*"
  - apiGroups:
      - rbac.crd.gocardless.com
    resources:
      - directoryrolebindings
    verbs:
      - "*"
  # The following permissions are provided to allow the manager to create roles
  # with these permissions
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - get
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
      - pods/attach
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workloads-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workloads-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workloads-manager
subjects:
  - kind: ServiceAccount
    name: workloads-manager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workloads-manager
  labels:
    group: workloads.crd.gocardless.com
spec:
  serviceName: workloads-manager
  volumeClaimTemplates: []
  selector:
    matchLabels:
      group: workloads.crd.gocardless.com
  template:
    metadata:
      labels:
        group: workloads.crd.gocardless.com
    spec:
      serviceAccountName: workloads-manager
      terminationGracePeriodSeconds: 10
      containers:
        - command:
            - /usr/local/bin/workloads-manager
          args:
            - --metrics-address=0.0.0.0
          image: gcr.io/duffel-shared/theatre:latest
          imagePullPolicy: Always
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: 9525
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
