---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag', 'eu.gcr.io/$PROJECT_ID/theatre:$SHORT_SHA',
    '--file', 'Dockerfile',
    '.'
  ]

images: [
  'eu.gcr.io/$PROJECT_ID/theatre:$SHORT_SHA'
]

options:
  machineType: 'E2_MEDIUM'