---
version: 2

references:
  docker_golang: &docker_golang
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/gocardless/theatre

jobs:
  check-generated-resources:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: Install prettier
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x > setup-node_10.x
            chmod +x setup-node_10.x && ./setup-node_10.x
            apt install nodejs
            npm install -g prettier
      - run:
          name: Ensure generated CRDs and RBAC are up to date
          command: make manifests && git diff --exit-code config/

  # Dependabot doesn't support vendoring module updates, so we use this CI step
  # to check we haven't updated our go.sum/go.mod without also vendoring the
  # dependencies.
  check-updated-vendor:
    <<: *docker_golang
    steps:
      - checkout
      - run: go mod vendor
      - run: go mod tidy
      - run: |
          if ! git diff --summary; then
            echo "vendor is out of date, please go mod vendor/tidy!"
            /bin/false
          fi

  unit-integration:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: Install ginkgo test runner
          command: go get github.com/onsi/ginkgo/ginkgo
      - run:
          name: Install Kubebuilder test helpers
          command: |
            mkdir /usr/local/kubebuilder
            curl -fsL https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.7/kubebuilder_1.0.7_linux_amd64.tar.gz \
              | tar -xvz --strip=1 -C /usr/local/kubebuilder
      - run:
          name: Run tests
          command: ginkgo -race -r -v

  build:
    <<: *docker_golang
    steps:
      - checkout
      - run:
          name: Build test binaries
          command: make all
      - persist_to_workspace:
          root: /go/src/github.com/gocardless/theatre
          paths: ['bin']

  acceptance:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Install tooling
          command: |
            sudo bash <<EOF
            curl -fsL -o /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64
            curl -fsL -o /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.11/kustomize_1.0.11_linux_amd64
            curl -fsL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.12/bin/linux/amd64/kubectl

            chmod a+x /usr/local/bin/kustomize /usr/local/bin/kubectl /usr/local/bin/kind
            EOF
      # Sleep to wait for everything to install properly before beginning tests
      - run:
          name: Prepare the cluster
          command: workspace/bin/acceptance prepare --bin workspace/bin && sleep 10
      - run:
          name: Run acceptance tests
          command: workspace/bin/acceptance run --verbose
      # If the test failed due to a flake then we want to gather as much
      # information as possible, because it could be hard to reproduce.
      - run:
          name: Show events
          command: KUBECONFIG="$(kind get kubeconfig-path --name="e2e")" kubectl get events
          when: on_fail
      - run:
          name: Show workloads logs
          command: KUBECONFIG="$(kind get kubeconfig-path --name="e2e")" kubectl -n theatre-system logs theatre-workloads-manager-0
          when: on_fail
      - run:
          name: Show rbac logs
          command: KUBECONFIG="$(kind get kubeconfig-path --name="e2e")" kubectl -n theatre-system logs theatre-rbac-manager-0
          when: on_fail

workflows:
  version: 2
  build-integration:
    jobs:
      - check-generated-resources
      - check-updated-vendor
      - unit-integration
      - build
      - acceptance:
          requires: [build]
