---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: workloads
  annotations:
    cert-manager.io/inject-ca-from: theatre-system/theatre-workloads-manager
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      caBundle: Cg==
      service:
        name: theatre-workloads-manager
        namespace: theatre-system
        path: /mutate-consoles
        port: 443
    name: console-authenticator.workloads.crd.gocardless.com
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    rules:
      - apiGroups:
          - workloads.crd.gocardless.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - consoles
        scope: '*'
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: workloads
  annotations:
    cert-manager.io/inject-ca-from: theatre-system/theatre-workloads-manager
webhooks:
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      caBundle: Cg==
      service:
        name: theatre-workloads-manager
        namespace: theatre-system
        path: /validate-consoleauthorisations
        port: 443
    name: console-authorisation.workloads.crd.gocardless.com
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    rules:
      - apiGroups:
          - workloads.crd.gocardless.com
        apiVersions:
          - v1alpha1
        operations:
          - UPDATE
        resources:
          - consoleauthorisations
        scope: '*'
    sideEffects: None
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      caBundle: Cg==
      service:
        name: theatre-workloads-manager
        namespace: theatre-system
        path: /validate-consoletemplates
        port: 443
    name: console-template-validation.workloads.crd.gocardless.com
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    rules:
      - apiGroups:
          - workloads.crd.gocardless.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - consoletemplates
        scope: '*'
    sideEffects: None
  - admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      caBundle: Cg==
      service:
        name: theatre-workloads-manager
        namespace: theatre-system
        path: /observe-console-attach
        port: 443
    name: console-attach-observer.workloads.crd.gocardless.com
    namespaceSelector:
      matchExpressions:
        - key: control-plane
          operator: DoesNotExist
    rules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CONNECT
        resources:
          - pods/attach
        scope: '*'
    sideEffects: NoneOnDryRun
    failurePolicy: Ignore # Ignore failures as we want to record attachment, but not at the cost of blocking connections
